[package]
name = "rivete-core"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
lifecycle = { workspace = true }
exn = { workspace = true }
derive_more = { workspace = true }
cfg-rs = { workspace = true }